# Generated by Django 3.0.8 on 2020-07-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200708_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='contenu',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(max_length=100),
        ),
    ]
