# Generated by Django 2.0 on 2020-07-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_article_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='photo',
        ),
    ]
